version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=bn_orangehrm
      - MARIADB_DATABASE=bitnami_orangehrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  orangehrm:
    image: bitnami/orangehrm:latest
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_USER=bn_orangehrm
      - ORANGEHRM_DATABASE_NAME=bitnami_orangehrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8383:80'
      - '443:443'
    volumes:
      - 'orangehrm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  orangehrm_data:
    driver: local
